# name: Deploy GitHub Pages

# # 触发条件：在 push 到 master 分支后
# on:
#   push:
#     branches:
#       - main

# # 任务
# jobs:
#   build-and-deploy:
#     # 服务器环境：最新版 Ubuntu
#     runs-on: windows-2019
#     steps:
#       # 拉取代码
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false

#       # 生成静态文件
#       - name: Build
#         run: npm install --registry=https://registry.npm.taobao.org && npm run build

#       # 部署到 GitHub Pages
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BRANCH: main
#           FOLDER: /dist
name: Static Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: actions/setup-node@master
      - run: npm install --registry=https://registry.npm.taobao.org
      - run: npm run build

      - name: Package Dist
        run: tar -zcvf release.tgz -C $GITHUB_WORKSPACE/dist .

      - name: Display Contents
        run: ls -R
        
      - name: Deploy to Server  # 第四步，rsync推送文件
        uses: AEnterprise/rsync-deploy@v1.0  # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}   # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc'   # rsync参数，排除.pyc文件
          SERVER_PORT: '22'  # SSH端口
          FOLDER: ./dist/*  # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SERVER_IP }}  # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: 'Administrator' # 引用配置，服务器登录名
          SERVER_DESTINATION: /nginx-1.25.3/html   # 部署到目标文件夹

      # Add your subsequent steps here


