# name: Deploy GitHub Pages

# # 触发条件：在 push 到 master 分支后
# on:
#   push:
#     branches:
#       - main

# # 任务
# jobs:
#   build-and-deploy:
#     # 服务器环境：最新版 Ubuntu
#     runs-on: windows-2019
#     steps:
#       # 拉取代码
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false

#       # 生成静态文件
#       - name: Build
#         run: npm install --registry=https://registry.npm.taobao.org && npm run build

#       # 部署到 GitHub Pages
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BRANCH: main
#           FOLDER: /dist
name: Static Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: actions/setup-node@master
      - run: npm install --registry=https://registry.npm.taobao.org
      - run: npm run build

      - name: Package Dist
        run: tar -zcvf dist.tgz -C $GITHUB_WORKSPACE/dist .

      - name: Display Contents
        run: ls -R
        
      - name: scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.SERVER_IP }}
          user: 'Administrator'
          pass: ${{ secrets.SERVER_PASSWORD }}
          scp: |
            ./dist.tgz => /nginx-1.25.3/html
          last_ssh: |
            cd /nginx-1.25.3/html/
            tar zxvf dist.tgz
            # 如果需要删除压缩文件，可以添加以下命令
            rm dist.tgz

      # Add your subsequent steps here


